language: node_js
if: branch != gh-pages
node_js:
  - "lts/*"
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install: "yarn install --frozen-lockfile"
script: "yarn ci"
